name: heightmap
dependencies:
  - python=3
  - pytest
  - gunicorn
  - numpy
  - h5py
  - gdal
  - pip
  - pip:
    - pygeodesy
    - geojson
    - fastapi
    - uvicorn
    - aiofiles
    - simplification
